### ISSUE TITLE
Incompatible with Carpet mod option

### ISSUE THREAD

**Issue by HDBuster** [Superkat32/Explosive-Enhancement#12]
Using **/carpet optimizedTNT true** with Explosive Enhancement only shows vanilla TNT explosions.

**/carpet optimizedTNT false** fixes it instantly.

Mod list (Quilt, 1.19.2):
Carpet,
Carpet-Fixes,
Explosive Enhancement,
Indium,
Iris Shaders,
Lithium,
Open Simple Frames,
Quilted Fabric API,
Sodium,
Sodium Extra,
YetAnotherConfigLib

**Comment by Superkat32** [comment]
I will not be fixing this, as it would require an insane amount of work on both my code and Carpet's code to fix. Please disable the gamerule instead.
