### ISSUE TITLE
[Suggestion] Minecraft trailers visual effects mod

### ISSUE THREAD

**Issue by mateus3c** [Superkat32/Explosive-Enhancement#13]
Ok so we all know that there is a mod that is almost that (effective) even tho its not really 100% based on MC trailers, but we also all know that effective is quilt only and sadly its creator doesnt allows ports anymore.
The idea behind a mod that adds MC's trailers visuals is to make the game feel more alive and dynamic. Here are some examples of visuals that would be great to have:

Visual wind on cold biomes
wavy camera screen when on a very hot biome or next to lava
water splash
cascade particles so we can feel the intensity when water falls
knockback particles when hit by something intense that knocks the entity out, like the goat dash, the trident, knockback sword, etc.

theres too many stuff to write here but you can see everything on: https://www.youtube.com/watch?v=RldSuJssVwQ

**Comment by mateus3c** [comment]
(just updated the comment because i posted it before i finish writing lol)

**Comment by Superkat32** [comment]
I personally think it is better to focus on one thing for a mod. Kitchen sink mods(mods that just add a bunch of random stuff for no reason) aren't really great user experiences 99% of the time(in my opinion). I prefer mods that focus on a specific thing, and do it really well. There are also multiple mods and resource packs that already add things from the trailers. Trying to do all of it in one mod would cause compatibility issues. However, taking one of your suggestions and turning it into a single, high effort mod isn't a bad idea.

On that note, however, I ask that you keep issues made on my repositories related to the project itself. This is to help make sure that I'm able to keep things organized. I would like to point out that I'm not upset, just a little something to keep in mind for the future 😃
