### ISSUE TITLE
Explosion effect not showing

### ISSUE THREAD

**Issue by Abicce** [Superkat32/Explosive-Enhancement#14]
I'm playing on the latest version available for Quilt 1.19.2, and none of the effects are showing. I've checked the configuration settings and I have everything enabled :(

**Comment by Superkat32** [comment]
While I can't guarantee support for Quilt, as it is not the platform Explosive Enhancement is designed for, I did do a quick test myself and it worked fine. 

 - What other mods are you using?
 - Do you have the right Explosive Enhancement version?
 - Are the vanilla particles showing?

**Comment by Abicce** [comment]
> 

hi, thanks for checking this issue out! I’ve tried using the mod without any other mod installed except for YetAnotherConfigLib, Mod menu, and the API for Quilt, all of which are the latest available version for Fabric/Quilt 1.19.2, so this probably isn’t an incompatibility issue. The version of this mod I’m using is 1.2.0 for Fabric 1.19.2 released on 25 July, downloaded from Modrinth. I do, however, have my particles set to “minimal” could that be the cause of the issue?

**Comment by Superkat32** [comment]
> I do, however, have my particles set to “minimal”

Thanks for pointing that out. I believe that is the issue. Could you try turning your particles to "All" and see what happens?

**Comment by Abicce** [comment]
> > I do, however, have my particles set to “minimal”
> 
> Thanks for pointing that out. I believe that is the issue. Could you try turning your particles to "All" and see what happens?

I've just tried this and it works! It works on Quilt, and with 'decreased' particle settings too :D so it seems that particles do not show at all with the 'minimal' setting. Thanks for the help! I'll close this issue now

**Comment by Superkat32** [comment]
Glad you figured it out! Hopefully you can have some fun with my mod!
