### ISSUE TITLE
Forge 1.20.1?

### ISSUE THREAD

**Issue by SafeOfArsenal** [Superkat32/Explosive-Enhancement#16]

**Comment by Superkat32** [comment]
I don't have any plans for officially supporting Forge. However, last time I checked, Explosive Enhancement(and a few other client-side mods of mine) worked flawlessly with Sinytra Connector. 

https://modrinth.com/mod/connector
https://github.com/Sinytra/Connector

I'd recommend checking it out! It's really cool!

**Comment by gitguette** [comment]
i tried this out on connector, the mod loads and shows config, but the effect doesn't render

**Comment by Superkat32** [comment]
> i tried this out on connector, the mod loads and shows config, but the effect doesn't render

I don't have time to test it out myself right now(maybe in an hour or two), but can you check if your particle visibility is set to all?

**Comment by gitguette** [comment]
yep

**Comment by Superkat32** [comment]
> yep

Worked perfectly fine for me...? What other mods are you using?

**Comment by gitguette** [comment]
Minecraft log says:
 [✔] 3dskinlayers-forge-1.5.4-mc1.20.1
  [✔] ad_astra-forge-1.20.1-1.15.3
  [✔] AdvancementPlaques-1.20.1-forge-1.4.10
  [✔] advancementscreenshot-1.20.1-4.2
  [✔] aether-1.20.1-1.0.0-beta.1.2-neoforge
  [✔] alexsmobs-1.22.6
  [✔] AmbientEnvironment-forge-1.20.1-11.0.0.1
  [✔] AmbientSounds_FORGE_v5.2.22_mc1.20.1
  [✔] appleskin-forge-mc1.20.1-2.5.0
  [✔] aquacombat+1.1
  [✔] aquamirae-6.API15
  [✔] archbows-1.1.8-1.20.1
  [✔] architectury-9.1.12-forge
  [✔] artifacts-forge-9.1.0
  [✔] auditory-0.0.6-1.20.1
  [✔] backpacked-forge-1.20.1-2.2.5
  [✔] badpackets-forge-0.4.2
  [✔] balm-forge-1.20.1-7.1.4
  [✔] bclib-3.0.13
  [✔] bedspreads-forge-6.2.0+1.20.1
  [✔] bendy-lib-forge-4.0.0
  [✔] BetterAdvancements-1.20.1-0.3.2.161
  [✔] bettercombat-forge-1.7.3+1.20.1
  [✔] BetterCompatibilityChecker-forge-4.0.8+mc1.20.1
  [✔] BetterF3-7.0.1-Forge-1.20.1
  [✔] better-nether-9.0.9
  [✔] BetterThirdPerson-Forge-1.20-1.9.0
  [✔] blur-forge-3.1.0
  [✘] BOMD-1.7.2-1.20.jar (disabled)
  [✔] Bookshelf-Forge-1.20.1-20.0.4
  [✔] botarium-forge-1.20.1-2.2.0
  [✔] caelus-forge-3.1.0+1.20
  [✔] CameraOverhaul-1.4.0-fabric-universal
  [✔] camerautils-1.20.1-1.0.5
  [✔] capybaramod-1.20.1
  [✘] cardinal-components-api-5.2.2.jar (disabled)
  [✔] cataclysmiccombat+1.1
  [✔] catalogue-forge-1.20.1-1.7.1
  [✔] cfm-forge-1.20.1-7.0.0-pre36
  [✔] chat_heads-0.10.22-forge-1.20
  [✔] Chunky-1.3.92
  [✔] cinderscapes-4.0.8
  [✔] citadel-2.4.4-1.20.1
  [✔] citresewn-1.20.1-3
  [✔] ClearDespawn-forge-1.20.1-1.1.13
  [✔] cloth-config-11.1.106-fabric
  [✔] collective-1.20.1-6.66
  [✔] combatroll-forge-1.2.1+1.20.1
  [✔] comforts-forge-6.3.3+1.20.1
  [✔] configured-forge-1.20.1-3.0.0
  [✔] connectiblechains-2.2.1+1.20.1
  [✔] Connector-1.0.0-beta.17+1.20.1+dev-g5f4d7cd-full
  [✔] Continents_1.20.1_v1.1.2
  [✔] Controlling-forge-1.20.1-12.0.2
  [✘] craftingtweaks-forge-1.20-18.2.1.jar (disabled)
  [✔] create-1.20.1-0.5.1.d
  [✔] createbb-1.20.1-3.1.1
  [✔] createbigcannons-forge-1.20.1-0.5.2.a
  [✔] create-confectionery1.20.1_v1.0.9
  [✔] createdieselgenerators-1.20.1-1.1c
  [✔] create_enchantment_industry-1.20.1-for-create-0.5.1.d-1.2.6.c
  [✔] createendertransmission-2.0.4-1.20.1
  [✔] Create-Guardian-Beam-Defense-1.2.9b-1.20.1
  [✔] create_jetpack-forge-4.0.2
  [✔] create_misc_and_things_+1.20.1_4.0A
  [✔] create-structures-0.1.1-1.20.1-FORGE
  [✔] create-stuff-additions1.20.1_v2.0.4a
  [✔] CreativeCore_FORGE_v2.10.34_mc1.20.1
  [✔] creeperoverhaul-3.0.1-forge
  [✔] ctov-3.3.4
  [✔] CullLessLeaves-1.3.0
  [✔] curios-forge-5.3.1+1.20.1
  [✔] curious_armor_stands-1.20-5.0.1
  [✔] customizableelytra-forge-2.1.0+1.20
  [✔] cyanide-forge-1.20-4.0.0
  [✔] Debugify-1.20.1+2.0
  [✔] deeperdarker-forge-1.20.1-1.2.0
  [✔] DiagonalFences-v8.0.1-1.20.1-Forge
  [✔] DiagonalWindows-v8.0.1-1.20.1-Forge
  [✔] do-a-barrel-roll-3.3.1+1.20-fabric
  [✔] domesticationinnovation-1.7.0-1.20
  [✔] doubledoors-1.20.1-5.0
  [✘] dropz-forge-2.2.0+1.20.1.jar (disabled)
  [✔] EasyAnvils-v8.0.1-1.20.1-Forge
  [✔] EasyMagic-v8.0.1-1.20.1-Forge
  [✔] EasyShulkerBoxes-v8.0.0-1.20.1-Forge
  [✔] eatinganimation-1.20-5.0.0
  [✔] Emojiful-Forge-1.20.1-4.2.0
  [✔] emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge
  [✔] EnchantmentDescriptions-Forge-1.20.1-17.0.5
  [✔] endertrigon-1.20.1-1.0
  [✔] endrem_forge-5.2.3-R-1.20.X
  [✔] EnhancedVisuals_FORGE_v1.6.6_mc1.20
  [✔] entity_model_features_forge_1.20-1.0
  [✔] entity_texture_features_forge_1.20-4.5.1
  [✔] everycomp-1.20-2.6.7
  [✔] exordium-forge-1.2.1-mc1.20.1
  [✔] explosive-enhancement-1.2.1-1.20.x
  [✔] extendedgears-2.1.0-1.20.1-0.5.1.c-forge
  [✘] extra-sounds-2.3.1+1.20.1~lonefelidae16-build.1.jar (disabled)
  [✔] fabric-api-0.89.0+1.9.21+1.20.1
  [✔] fabric-language-kotlin-1.10.10+kotlin.1.9.10
  [✔] Fallingleaves-1.20.1-2.1.0
  [✔] FarmersDelight-1.20.1-1.2.3
  [✔] Fastload-Reforged-mc1.20.1-3.4.0
  [✔] ferritecore-6.0.0-forge
  [✔] fireworkfrenzy-1.5-1.20.1
  [✔] framework-forge-1.20.1-0.6.16
  [✔] gamemenumodoption-mc1.20.1-2.2.1
  [✔] geckolib-forge-1.20.1-4.2.2
  [✔] gml-4.0.4-all
  [✔] gravestone-1.20.1-1.0.5
  [✔] HopoBetterRuinedPortals-[1.20-1.20.1]-1.3.6
  [✔] HopoBetterUnderwaterRuins-[1.20-1.20.1]-1.1.3b
  [✔] HorseExpert-v8.0.1-1.20.1-Forge
  [✔] Iceberg-1.20.1-forge-1.1.13
  [✘] ImmediatelyFast-1.2.5+1.20.2.jar (disabled)
  [✔] immersive_aircraft-0.6.2+1.20.1-forge
  [✔] immersive_armors-1.6.1+1.20.1-forge
  [✔] improvedmobs-1.20.1-1.11.5-forge
  [✔] incapacitated-1.20.1-1.4.4.2
  [✔] Incendium_1.20.1_v5.3.1
  [✔] infernalmobs-1.20.1.0
  [✔] InvMove-1.20-0.8.4-Forge
  [✔] irons_spellbooks-1.20.1-1.2.1
  [✔] Jade-1.20.1-forge-11.6.1
  [✔] kaffees_dual_ride-1.1.0
  [✔] Kiwi-1.20.1-forge-11.1.1
  [✔] knavesneeds-forge-1.1.5.2+1.20.1
  [✔] kotlinforforge-4.3.0-all
  [✔] KryptonReforged-0.2.3
  [✔] leap-1.20.1-1.1.2
  [✔] L_Enders_Cataclysm-1.29-1.20.1
  [✔] LetSleepingDogsLie-1.20.1-Forge-1.2.0
  [✔] LongerChatHistory-1.3-Forge
  [✔] lootr-1.20-0.7.30.73
  [✔] make_bubbles_pop-0.2.0-forge-mc1.19.4+
  [✔] mcw-fences-1.0.7-mc1.20.1forge
  [✔] midnightlib-fabric-1.4.1
  [✔] mixintrace-1.1.1+1.17
  [✔] modelfix-1.14
  [✔] modernfix-forge-5.7.4+mc1.20.1
  [✔] ModifierKeyFix-1.0.0
  [✘] MonsterPlus-Forge1.20.1-v1.1.6.1.jar (disabled)
  [✔] moonlight-1.20-2.8.35-forge
  [✔] morebannerfeatures-1.2.0-1.20
  [✔] morediscs-1.20.1-30-forge
  [✔] MouseTweaks-forge-mc1.20-2.25
  [✔] MutantMonsters-v8.0.4-1.20.1-Forge
  [✔] nethersdelight-1.20.1-4.0
  [✔] notenoughanimations-forge-1.6.4-mc1.20
  [✔] Nullscape_1.20.1_v1.2.2
  [✔] nyfsspiders-forge-1.20.1-2.1.1
  [✔] obscure_api-15
  [✔] Obscure-Tooltips-2.2
  [✔] oculus-mc1.20-1.6.4
  [✔] Paraglider-forge-20.1.1
  [✔] ParCool-1.20.1-3.1.0.3-R
  [✔] Patchouli-1.20.1-81-FORGE
  [✔] Pehkui-3.7.8+1.20.1-forge
  [✔] physics-mod-pro-v160-forge-1.20.1
  [✔] piglinproliferation-1.20-1.1.1
  [✔] player-animation-lib-forge-1.0.2-rc1+1.20
  [✔] PresenceFootsteps-1.9.0
  [✔] PuzzlesLib-v8.0.24-1.20.1-Forge
  [✔] Random+Crits+1.0.2+-+1.20.1
  [✘] rats-8.0.6-1.20.1.jar (disabled)
  [✔] rayon-forge-1.7.2+1.20.1
  [✔] resourcefulconfig-forge-1.20.1-2.1.0
  [✔] resourcefullib-forge-1.20.1-2.1.11
  [✔] riverredux-0.3.1
  [✔] RoughlyEnoughItems-12.0.659
  [✔] rubidium-0.6.5
  [✔] scuba_gear-1.20.1-1.0.6
  [✔] sculkhorde-1.20.1-0.7.0
  [✔] Searchables-forge-1.20.1-1.0.1
  [✔] SereneSeasons-1.20.1-9.0.0.43
  [✔] simplyswords-forge-1.51.0-1.20.1
  [✔] sliceanddice-forge-3.1.2
  [✔] slimy-stuff-1.20.1-1.0.9
  [✔] smallships-forge-1.20.1-2.0.0-a2.3.3
  [✔] smoothswapping-0.9.2-1.20-fabric
  [✔] soundphysics-forge-1.20.1-1.2.1
  [✔] SpelunkersCharm-3.4.1-1.20.1
  [✘] srcmovement-1.20.1.jar (disabled)
  [✔] stalwart-dungeons-1.20.1-1.2.8
  [✔] starlight-1.1.2+forge.1cda73c
  [✔] statuseffecttimer-1.1.1+1.20.1
  [✔] Steam_Rails-1.5.1+forge-mc1.20.1
  [✔] structure_gel-1.20.1-2.13.1
  [✔] tectonic-mod-mc1.19.3+-v2.1
  [✔] tenshilib-1.20.1-1.7.0-forge
  [✔] TerraBlender-forge-1.20.1-3.0.0.169
  [✔] Terralith_1.20.1_v2.4.5
  [✔] tidal-towns-1.2
  [✔] toofast-1.20-0.4.3.5
  [✔] totw_modded-1.0.1-1.20.1
  [✔] transportables-1.20.1
  [✔] TravelersTitles-1.20-Forge-4.0.1
  [✔] twilightforest-1.20.1-4.3.1846-universal
  [✔] voicechat-forge-1.20.1-2.4.24
  [✔] waystones-forge-1.20-14.0.2
  [✔] witherstormmod-1.20.1-4.0
  [✔] XaeroPlus-Forge-1.20.1-40-WM1.34.1-MM23.8.2
  [✔] Xaeros_Minimap_23.8.2_Forge_1.20
  [✔] XaerosWorldMap_1.34.1_Forge_1.20
  [✔] yet-another-config-lib-forge-3.2.1+1.20
  [✔] YungsApi-1.20-Forge-4.0.1
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.1
  [✔] YungsBetterDungeons-1.20-Forge-4.0.1
  [✔] YungsBetterJungleTemples-1.20-Forge-2.0.1
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.1
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.2
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.1
  [✔] YungsBetterStrongholds-1.20-Forge-4.0.1
  [✔] YungsBetterWitchHuts-1.20-Forge-3.0.1
  [✔] YungsBridges-1.20-Forge-4.0.1
  [✔] YungsExtras-1.20-Forge-4.0.1
