### ISSUE TITLE
1.18.2 plz

### ISSUE THREAD

**Issue by dirtysheep233** [Superkat32/Explosive-Enhancement#19]

**Comment by Superkat32** [comment]
If I can do it in like, 30 minutes, then sure. It won't continue to be supported with updates, and if there are bugs, I'm probably not going to be fixing them, but it'll give you something to have(likely to be only uploaded here on GitHub). Not happening right now, but I will try to get to that soon:tm:

**Comment by Fefedu973** [comment]
NICE !

**Comment by Superkat32** [comment]
Did I forget about this? What?? N-_noooooo..._ yes. But, here you go.

https://github.com/Superkat32/Explosive-Enhancement/releases/tag/1.2.2-1.18.2

Requires Fabric API. Config should be able to be edited using the file, but not via mod menu. I haven't tested it outside of the development environment, but it should still work.

**Comment by SergenteDonato02** [comment]
> Did I forget about this? What?? N-_noooooo..._ yes. But, here you go.
> 
> https://github.com/Superkat32/Explosive-Enhancement/releases/tag/1.2.2-1.18.2
> 
> Requires Fabric API. Config should be able to be edited using the file, but not via mod menu. I haven't tested it outside of the development environment, but it should still work.

Please update it on modrith.

Thanks.
