### ISSUE TITLE
[Mod Idea] Lightning Enhancement

### ISSUE THREAD

**Issue by Puffadillo** [Superkat32/Explosive-Enhancement#20]
Apologies, I know the GitHub issue tracker probably isn't meant for stuff like this, but I didn't see any other way of commenting/sending a message.

Anyway, I'm a big fan of Explosive Enhancement. Explosion animations were something I thought needed improvement for the longest time, considering how powerful they are. The animations and attention to detail really stand out in this mod, and I really love it overall.

That being said, have you considered doing the same for lightning strikes? That's another impactful gameplay element that I feel would benefit from some animation overhauls, considering how bare-bones the vanilla effect is. Anyway, feel free to close this issue. Just wanted to share an idea in case it sounds interesting, and thanks for developing your mods.

**Comment by Superkat32** [comment]
I've actually had a lightning strike overhaul mod idea on my mod lists for months now. I decided to wait until I got better at in-game in-world rendering before attempting it though. My original idea mostly overhauled the actual look of the lightning strike, but I agree with the impact probably needing some love as well. 

I doubt I'll get started on it anytime soon as I'm only now getting into the light end of in-world rendering, however, if you still want a nice lightning mod, there is this one which I've been using for a while.

https://modrinth.com/mod/immersivethunder

It sounds really nice above ground, and also plays obstructed lightning sounds when underground to a degree. I've only ever used it with combination of Sound Physics Remastered, so I'm not sure how much of it is being carried by Sound Physics Remastered, but I think it should still sound nice without it.
