### ISSUE TITLE
The mod doesn't work for me, I installed that config mod as well as mod menu.

### ISSUE THREAD

**Issue by 253488655422** [Superkat32/Explosive-Enhancement#23]
The mod didn't work, explosions were pretty much the same I went into the mod menu and clicked the properties button thing for the mod and it showed the config but it seemed to be gray I was able to change the settings though but not for sizing or extra the buttons disappeared when I clicked on them.
(I am using Fabric)
Here is a list of mods I have: 
![Screenshot (843)](https://github.com/Superkat32/Explosive-Enhancement/assets/35547883/8e4ae25e-7a27-4ca3-9e95-1c635e99d0c3)

**Comment by Superkat32** [comment]
1. Do you actually have Explosive Enhancement installed? It isn't shown in your mod list screenshot.
2. Are your particle settings set to "all"? (Found in `Options > Video Settings > Particles`. Also found in `Options > Video Settings > Quality > Particles` if you are using Sodium)
3. Do you have the latest version of YetAnotherConfigLib? I've never heard of that issue with the buttons being grey. Is it a resource pack doing it?

**Comment by 253488655422** [comment]
1. Yes it does show up I said it was greyed out for a reason in the config 
2.  No it's set to minimal
3.  I turned off every resource pack but I didn't want to remove any mods.

**Comment by Superkat32** [comment]
Try setting your particles to "all", or enabling the "Always Show Particles" config option(found in the `Extra` tab of the Explosive Enhancement config). I believe that is the issue.

**Comment by 253488655422** [comment]
Ok I'll set it to all but the extra tab nothing showed up

**Comment by 253488655422** [comment]
is there way to turn on specific particles for the mod because I remember my performance went down when I had particles set to all.

**Comment by Superkat32** [comment]
Oh, so you don't see this config tab at all?
![image](https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/79faec52-26c1-4f60-9ad8-2406b19c78da)

**Comment by 253488655422** [comment]
No.

**Comment by 253488655422** [comment]
I only saw Particles.

**Comment by Superkat32** [comment]
Can you send a screenshot? If you can't then that's fine.

**Comment by 253488655422** [comment]
Sure let me just boot up minecraft and my server.

**Comment by Superkat32** [comment]
No need to boot up the server, you should only need to stay in the menu screen and join a singleplayer superflat world or something like that.

**Comment by 253488655422** [comment]
ok.

**Comment by 253488655422** [comment]
My laptop is being dum so it'll take another minute

**Comment by Superkat32** [comment]
Worst case scenario, you can also manually enable the config option in a text editor by going to `.minecraft > config > explosiveenhancement.json` and setting the "always_show" config option towards the bottom to `  "always_show": true` . You might have to restart your game for that to be applied, I'm not actually sure.

**Comment by 253488655422** [comment]
ok here are some screenshots:
![Screenshot (844)](https://github.com/Superkat32/Explosive-Enhancement/assets/35547883/dd257fc5-8686-48f3-b5d7-9f56c5d6be08)
![Screenshot (845)](https://github.com/Superkat32/Explosive-Enhancement/assets/35547883/05d934a2-f4b1-4310-b233-85fc4ff1222c)
![Uploading Screenshot (846).png…
![Screenshot (847)](https://github.com/Superkat32/Explosive-Enhancement/assets/35547883/08b16105-e5c5-454b-8f55-734d6dec0f59)
![Screenshot (848)](https://github.com/Superkat32/Explosive-Enhancement/assets/35547883/5368f6ad-9751-4add-85a3-afbd2b9813a5)

]()

**Comment by 253488655422** [comment]
I didn't turn on particles

**Comment by 253488655422** [comment]
nope it's still the same with particles on.

**Comment by Superkat32** [comment]
Whatever is allowing the panorama to be rendered in the menus seems to be messing something up.

**Comment by 253488655422** [comment]
oh mayve it's because bedrockify.

**Comment by Superkat32** [comment]
I tried using the same modlist(but latest mod version for everything) that you sent and everything works fine. Everything is on default settings though.

**Comment by 253488655422** [comment]
huh

**Comment by 253488655422** [comment]
I don't want to remove it I'll try editing the config with the json file first but I' m gonna eat dinner first. I'll let you know if it worked or not.

**Comment by Superkat32** [comment]
Alright. 👍

**Comment by Superkat32** [comment]
I think I figured it out, because I'm now able to replicate the issue.

Try following these steps.
Go to Panorama Screens mod's config
![image](https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/bb8442ce-8093-466b-aa1d-65878a53d9e5)

Open the Allow List option, and find `dev.isxander.yacl3.gui.YACLScreen`. Make sure to click on it(white line appears beneath) to select it.
![image](https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/2ef768d6-a3c0-484f-be4c-c0ca42dced77)

Scroll back up to the Allow List option at the top, and click the Delete Selected button.
![image](https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/9657f60e-9b11-475a-8562-6c8e4b6f3813)

You should be able to save and exit now and all YACL screens should be fixed(including Explosive Enhancement's config screen).

**Comment by 253488655422** [comment]
Ok I'll try that.

**Comment by 253488655422** [comment]
I don't see it, I think  that's another mod, I'll try installing Panorama Screens anyway and see if it has any difference.

**Comment by 253488655422** [comment]
I installed that mod and it's fixed, the config appeared and it's not greyed out anymore.

**Comment by 253488655422** [comment]
look it says mod enabled is false.
![Screenshot (850)](https://github.com/Superkat32/Explosive-Enhancement/assets/35547883/953d8c88-15d4-4c46-9265-a8e3e01a3a3b)

**Comment by Superkat32** [comment]
Great! You should be able to enable the "Show All Particles" setting in the Extras tab and the explosion effect should show on the minimal particles setting.

> look it says mod enabled is off.

Just click on "Mod Enabled" to turn it on.

**Comment by 253488655422** [comment]
Ok it works.

**Comment by 253488655422** [comment]
the explosions are working but the loading screen is messed up for bedrocify.

**Comment by Superkat32** [comment]
Did you only remove the `dev.isxander.yacl3.gui.YACLScreen` from the Allow List on the Panorama Screens config or did you remove more??

**Comment by 253488655422** [comment]
I didn't do anything I couldn't find the setting for it in the first place.

**Comment by 253488655422** [comment]
I checked allowedlist top from bottom

**Comment by 253488655422** [comment]
![Screenshot (851)](https://github.com/Superkat32/Explosive-Enhancement/assets/35547883/23c49adc-42d5-4616-8dbe-dfe3143513e5)

**Comment by Superkat32** [comment]
What is messed up with the Bedrockify loading screens? Is it no longer showing the panorama in the background?

**Comment by 253488655422** [comment]
it's suppose to be like bedrock

**Comment by Superkat32** [comment]
Do you see this by chance in Panorama Screens' Allow List?

![image](https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/2111c339-f558-4b49-8c34-e0e71e1312d7)

**Comment by 253488655422** [comment]
yes.

**Comment by Superkat32** [comment]
I have no idea then. I'm not familiar enough with Bedrockify or Panorama Screens to know what is going on.

If you want to try it, you could try clicking the Reset button the Allow List, but that will set all the screens that are allowed to have the panorama rendered to the default settings. Unless you've downloaded your mods from a modpack, or you've manually edited the config, this shouldn't really be a huge deal. Completely up to you. If the Reset Button is greyed out, then that means it is already the default settings.

**Comment by 253488655422** [comment]
yeah it's greyed out :)

**Comment by Superkat32** [comment]
Yeah I have no idea then.

**Comment by 253488655422** [comment]
I'll try removing Panorama Screens and see if it will change.

**Comment by 253488655422** [comment]
It's just the default java loading screen. It's whatever I guess.

**Comment by Superkat32** [comment]
I'm closing this issue since the problems with Explosive Enhancement have been solved. I'd say take a look at both Bedrockify's and Panorama Screen's GitHub pages and see if there is any issues(both open and closed) related to the issue you've suddenly gotten. I'm guessing it is a config problem.
