### ISSUE TITLE
doesnt work on hypixel

### ISSUE THREAD

**Issue by Thsgun** [Superkat32/Explosive-Enhancement#24]
![image](https://github.com/Superkat32/Explosive-Enhancement/assets/140964974/224d1f20-820e-463e-801a-0fc594f4cd2f)
![image](https://github.com/Superkat32/Explosive-Enhancement/assets/140964974/fb213add-033d-4232-81c7-c967465b4da2)

**Comment by Thsgun** [comment]
i tested it on singleplayuer and it works and i dont understand why

**Comment by Superkat32** [comment]
This is because Hypixel spawns in the explosion particles themselves, instead of actually creating an explosion. There's nothing I can realistically do about this.

**Comment by Thsgun** [comment]
ah ok, ty
