### ISSUE TITLE
[Feature Request:] Can you make this a resource pack?

### ISSUE THREAD

**Issue by JustD1v** [Superkat32/Explosive-Enhancement#25]
I couldn't find anywhere to contact, so I am contacting from here. I really like this mod it's so good, but I want to use this in vanilla as a resource pack, can you do that?

**Comment by Superkat32** [comment]
I mean, technically yes but not really. Imagine a normal Minecraft explosion, with the multiple white circles being spawned. You can change the texture of those white circles to the orange circles from my mod. However, there will still be multiple of them. You can't change that with a resource pack. That's handled exclusively by code.

But, if you still wanted to, you can try and change the white circles to the orange circles with a resource pack. If you've made a resource pack before, it should be a breeze. If you haven't, then this would be a great learning experience more than anything :)
I'm not sure if it'll look good, but you could take the skills learnt from that and apply it elsewhere.

https://github.com/Superkat32/Explosive-Enhancement/tree/master/src/main/resources/assets/explosiveenhancement/textures/particle

This is where the textures from my mod are located. You'll likely want to use the `fireball` textures.

**Comment by JustD1v** [comment]
Thank you so much, you are so kind and helpful, wish you the best of luck with modding.
