### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Ciellix** [Superkat32/Explosive-Enhancement#27]
Every so often my private server crashes and Iv come too find out its something to do with your mod (Sorry if Iv done any thing wrong on github, this is my first time using this site) [crash-2024-03-16_21.32.30-server.txt](https://github.com/Superkat32/Explosive-Enhancement/files/14626391/crash-2024-03-16_21.32.30-server.txt)
I was told this, when I asked someone for help "alessandrv-enchantments uses a null damage source when they hurt mobs which crashes our mixin but would crash vanilla anyway as damage sources have to be not null" idk if it helps or not.

**Comment by Superkat32** [comment]
I believe the issue actually has something to do with this mod.

https://github.com/alessandrv/alessandrv-enchantments

Explosive Enhancement is never mentioned in the log, including the mod list. A "Explosive En**chant**ment" file is mentioned quite a bit though, which is from the mod linked above. This enchantment seems to be causing the issue.

**Comment by Ciellix** [comment]
Oh I must have clicked the wrong github link, Im sorry about that, as I stated before I've never used this before, my bad, Thanks for sending me on the right path.

**Comment by Superkat32** [comment]
No worries!
