### ISSUE TITLE
New explosion effects aren`t visible on Aternos Server

### ISSUE THREAD

**Issue by Ford3l** [Superkat32/Explosive-Enhancement#29]
Hello! I`ve an issue, i don`t see new explosion effects on Aternos server. I use Synitra Connector and Embeddium. What files can i send to help you fix this...problem?

**Comment by Superkat32** [comment]
Support for Forge via Connector cannot be guaranteed. However, I'll try my best.

1. Are your particle settings set to "all"? (Found in `Options > Video Settings > Particles` for vanilla. Also found in `Options > Video Settings > Quality > Particles` for Sodium, it might be like that for Embeddium as well?)
2. Have you tested in singleplayer? I don't think the server provider would cause any issues.

**Comment by Superkat32** [comment]
Closing as the issue made on the Sinytra Connector repo was closed.
