### ISSUE TITLE
Withering Heights Mod/Datapack Uses Negative Explosions, Causing Disconnection While Fighting Wither

### ISSUE THREAD

**Issue by cobaltlol2** [Superkat32/Explosive-Enhancement#37]
https://pastebin.com/YBYG6XCi

**Comment by Superkat32** [comment]
Somehow it failed to spawn the 5th(out of 6) smoke particle??? 
- Did other explosions spawn before you crashed(if you can remember)?
- Are you able to reproduce the crash? If so, could you try testing with only Explosive Enhancement installed?

**Comment by cobaltlol2** [comment]
I was fighting the enhanced wither from the withering heights: revamped wither and he did the ground slam attack, and  immediately after it crashed.

**Comment by cobaltlol2** [comment]
Although I installed the methane mod to help with explosion performance and it seems to have fixed it?

**Comment by Superkat32** [comment]
Does it crash without Methane installed?

**Comment by cobaltlol2** [comment]
Yes, it's a "network protocol error" when the wither performs an attack. It's possible that methane doesn't really prevent this, I'll give it a try with methane again tomorrow to confirm that

**Comment by Superkat32** [comment]
While you're at it, maybe try without Explosive Enhancement installed and let me know the results please. I wonder if it is a mod compatibility issue with that wither mod you mentioned.

**Comment by cobaltlol2** [comment]
Yeah will do it tmr

**Comment by Superkat32** [comment]
Thanks! I'll also try to do some testing as well later tonight. My current guess is that it was a one time crash(computers aren't perfect), but I'm not super happy with that conclusion just yet.

**Comment by cobaltlol2** [comment]
Just tried it with methane on, and it does crash still, just takes quite a bit longer. Here's the disconnect log if u need: https://pastebin.com/bdh1eLLv. If you would like to test it out yourself, here's my modpack with all the mods: https://modrinth.com/modpack/true-vanilla+/version/wSLnwNCs , you just need to stall the wither long enough with instant hp and health boost and he will eventually make you DC

**Comment by Superkat32** [comment]
Having the modpack available to me is actually really helpful, thank you.

Just to clarify because I've gotten a bit confused, when you say "crash", are you referring to getting disconnected from the server(or singleplayer world) or having your game program fully close?

If you are just disconnecting from the server(or singleplayer world), I wonder if this issue is related to #35 . Maybe that wither mod is trying to use the same trick mentioned in the linked issue.

**Comment by Superkat32** [comment]
So I did some testing myself using the modpack you gave. I was able to fight the wither completely without getting disconnected, _however_, I tried spawning in explosions with negative power(what issue 35 did) and it provided the same error and stack trace you've linked.

Negative explosions sometimes, not all the time, cause disconnections with this mod, a known issue I know how to fix but haven't had the time for yet. I'm guessing then the Withering Heights mod/datapack uses negative explosions for a fancy effect, which sometimes causes you to disconnect.

I will try to get this fixed somewhat soon. I just need time for now.

**Comment by cobaltlol2** [comment]
You don't even need to fight the wither, just give yourself infinite hp and sit there for a few minutes, the wither should disconnect you after a while

**Comment by cobaltlol2** [comment]
> I will try to get this fixed somewhat soon. I just need time for now.
Ok thanks

**Comment by Superkat32** [comment]
(Hopefully) fixed! Let me know if you have any issues.
