### ISSUE TITLE
[Feature Request] Explosion Size should add up

### ISSUE THREAD

**Issue by Dashy22** [Superkat32/Explosive-Enhancement#39]
This might be a bit much but it would be cool if the size of the visual explosion would merge if enough tnt blew up in an area, so if you lit up a big box of tnt than a mini mushroom cloud would form or just the explosion itself you already had would just visually appear bigger.
It's ok if you can't do it this just seems cool.

**Comment by Superkat32** [comment]
I think that would be cool, but I personally think there's something really satisfying about seeing multiple explosions happen at once with all the smoke coming afterwards. Beyond that, I think it is slightly outside the scope of this mod's goal anyways.

**Comment by Dashy22** [comment]
ok yeah i kinda guessed that but thanks for giving an explanation though!
