### ISSUE TITLE
1.21.4 mod version

### ISSUE THREAD

**Issue by Waldachenn** [Superkat32/Explosive-Enhancement#43]
Hello!
Could you please add compatibility with 1.21.4 minecraft version.

![image](https://github.com/user-attachments/assets/5c030e0a-0ef2-4a70-9ea2-7c90672bb543)

**Comment by Superkat32** [comment]
I'm hoping to, yes! I've been working very hard on the 1.21.2/3/4 update for the past ~3 weeks, but Minecraft 1.21.2 changed a lot of the explosion's code, notably making the data used to scale explosions no longer usable on the client, meaning I need to figure out how to handle that. I'm getting close to being done, but will need more time to finish it up.

**Comment by Redguard1998** [comment]
Hi @Superkat32 I was wondering if you maybe have a Discord server or another platform? I'd love to see updates on stuff that you're working on. And i'm also patiently waiting on this mod to update to 1.21.3!!!

**Comment by Superkat32** [comment]
Finished! Please let me know if you have any issues.

**Comment by Superkat32** [comment]
> Hi @Superkat32 I was wondering if you maybe have a Discord server or another platform? I'd love to see updates on stuff that you're working on. And i'm also patiently waiting on this mod to update to 1.21.3!!!

I extremely rarely post things I'm working on in Fabric's Discord(showcase channel), but beyond that I think you're best bet is right here on GitHub because I don't usually post anywhere else.

**Comment by Redguard1998** [comment]
That's okay, don't worry, thank you so much for updating it. I've been patiently waiting for some time now. It is truly a really cool add-on :)
