### ISSUE TITLE
crash with new version

### ISSUE THREAD

**Issue by shinycolororange** [Superkat32/Explosive-Enhancement#44]
https://mclo.gs/hTuDsah

**Comment by Superkat32** [comment]
oh come on I thought I was free from the refmap error

**Comment by Superkat32** [comment]
Wait it works for me?????????????????

Can you try on a new instance with only the required mods(Fabric API, Mod Menu, YACL, Explosive Enhancement) on the same Minecraft version(1.21.1)?

**Comment by Superkat32** [comment]
I'm unable to reproduce this even on a new instance myself, but this was an issue I experienced(and seemingly fixed) on newer versions when testing.

It might be a mod conflict, I'm unsure. If anyone else is experiencing this issue, please mention so here(log or crash report would be very helpful). 

I'm going to leave this open for now. If you experience this issue even on a new instance with only the required mods, I can try a few things but I'm not sure if they'll work.

**Comment by shinycolororange** [comment]
here is a crash report on a fresh installed 1.21.1 fabric version with only this mod plus api and sodium/lithium this time it crashed when using tnt i also used java 23.0.1 // https://mclo.gs/YciITyX

**Comment by Superkat32** [comment]
Can you try with the test version here?
https://github.com/Superkat32/Explosive-Enhancement/releases/tag/1.3.1-1.21.1-refmapfixtest
(Only use the `explosive-enhancement-1.3.1-1.21-1.21.1.jar` file, the others won't help)

**Comment by shinycolororange** [comment]
fixed the issue even on my 200 mods modpack thanks :3

**Comment by Superkat32** [comment]
The test version? Nice!! I'll make sure to upload the fixed version tomorrow then.

Thanks for putting in effort and helping me, it may not seem like it but this actually helps a lot!
