### ISSUE TITLE
Crashes on start up 1.3.1-1.20.x - MC version 1.20.1

### ISSUE THREAD

**Issue by DTX3** [Superkat32/Explosive-Enhancement#46]
explosive-enhancement-1.2.2-1.20.x - works fine

explosive-enhancement-1.3.1-1.20.x - crashes.

MC version: 1.20.1

[crash-2024-12-20_18.14.18-client.txt](https://github.com/user-attachments/files/18214000/crash-2024-12-20_18.14.18-client.txt)

**Comment by Superkat32** [comment]
Should be fixed in 1.3.2. Let me know if you still have any issues. Thanks for reporting!

**Comment by DTX3** [comment]
Thanks! That fixed it ;)
