### ISSUE TITLE
Feature Request: Sparks Particle

### ISSUE THREAD

**Issue by Superkat32** [Superkat32/Explosive-Enhancement#6]
Add white(or brightly colored yellow) lines that would act like sparks.

First mentioned by BLUEChester, 

>You could also consider adding some additional particles, like some lines that shoot out, or dirt/sand particles. This would add some variety and make the effect look more detailed. 

_Originally posted by @BLUEChester in https://github.com/Superkat32/Explosive-Enhancement/issues/3#issuecomment-1510053988_

**Comment by Superkat32** [comment]
Started work on this. I believe the particle disappears slightly too fast, and the textures' colors could be changed slightly, but the overall shape and behavior of it is pretty much done.

https://user-images.githubusercontent.com/89557012/236350990-fee3313b-2837-4e17-970f-705d739aa599.mp4

**Comment by BLUEChester** [comment]
Ooo the spark animation looks really good. I just think there might be a little bit to much going on, with all these effects at the same time.

To improve the spark itself you should definitely add some transparency so it doesn't look quiet as bright, possibly make it slightly smaller, and most importantly it should appear later in the animation, more specifically after the vertical shockwave, so it seems like the spark appears because of the vertical shockwave.

I think these sparks should act as a very subtle and small effect 'caused' by the other shockwaves, rather then dragging the attention away from the rest of the animation. Which is personally what I think its doing at the moment.

Apologies if my feedback was a bit too harsh!

**Comment by Superkat32** [comment]
Honestly... Incredible call! I think it does look a lot better with a little bit of delay. I've made it so that the sparks spawn in whenever the vertical shockwave is around 65% through its animation.

I think I also did something with its transparency but I don't know how well that is being shown in the video, so that probably still needs work.

https://user-images.githubusercontent.com/89557012/236589453-9a02347a-37b5-448d-9889-f10ebf3a6a88.mp4

**Comment by IceBlossom** [comment]
Holy shit Chester... good suggestion! The effect looks insane now! I can't wait to see what it'll look like during Matrix in Hole in the Wall on MCC Island...
And good job to you Kat for making it look super good! I can't wait to see this mod version release! :D

**Comment by Superkat32** [comment]
OH MY GOSH The MCC Island thing LOLOLOLOL

**Comment by IceBlossom** [comment]
Yeah I can give you a video on how it looks if you send me a build of the mod in its current state (i can also check for mod incompatibility, as I have over 90 mods I use for vanilla)

**Comment by BLUEChester** [comment]
Yeah I definitely believe the delay looks way better, great stuff!

The spark should certainly be very slightly smaller still and yeah see if you can get the transparency a little bit more apparent, if its not possible then thats fine as it already looks really great.

I really appreciate that you originally did disagree with my idea as it is good to have some back and fourth, but even nicer that you still gave it a shot, thanks!

Thanks for your words IceBlossom!

**Comment by Superkat32** [comment]
> Yeah I can give you a video on how it looks if you send me a build of the mod in its current state (i can also check for mod incompatibility, as I have over 90 mods I use for vanilla)

Yes! I can put a beta release in the releases tab for the GitHub repo(as soon as I figure out how). Is MCC Island any specific version of 1.19? I only have 1.19.2 and 1.19.3, as the 1.19.4 port is yet to come.

**Comment by IceBlossom** [comment]
MCC Island switched to 1.19.4-only on April 19th.

**Comment by Superkat32** [comment]
Okay. I'll send you the 1.19.4 port as soon as I get started on it.

**Comment by Superkat32** [comment]
Sparks has been made smaller and less transparent. It is now only slightly bigger than the vertical shockwave effect.

https://user-images.githubusercontent.com/89557012/236641806-87295796-148f-40e8-91f9-cec78196afd1.mp4

**Comment by IceBlossom** [comment]
That looks pretty good! How's the progress on the 1.19.4 port?

**Comment by Superkat32** [comment]
The 1.19.4 port will either happen whenever I'm really bored or once all these new 1.1 features are completed(underwater explosions, config library switch, spark particle).

The underwater explosions are almost done, I've been meaning to play around with the bubbles' movement some more but been busy. Config library switch is also pretty much done, just have to remove a couple lines of code which still remain. And the spark particle is seemingly pretty close to done as well.

**Comment by BLUEChester** [comment]
Sounds good! Will the spark particle also be available for the underwater explosion?

**Comment by Superkat32** [comment]
Yes! It will even have its own config option separate from the on land sparks. That means you can disable the underwater sparks, but keep the on land sparks.

**Comment by Superkat32** [comment]
Quick video of the underwater sparks. I personally don't really like it all that much, as I think it pulls some of the attention away from the bubbles(which are the fun part imo), but that is why there is a config option to enable/disable it at will.

https://github.com/Superkat32/Explosive-Enhancement/assets/89557012/ba269e98-41e4-41ae-b33b-bbb97a692aed

**Comment by IceBlossom** [comment]
Seperate idea: What if you could make a config option to change the size of the sparks, instead of on and off, and have a setting for land explosions and one for water explosions.
You can tweak this for a default configuration that you like for base shipping, and then users can decide how big they want it. I feel like this could be a 1.2 feature though, we don't need a Minecraft mod turning into Geometry Dash's update cycle, haha.

**Comment by Superkat32** [comment]
If my understanding of particle factories(the particle's code) is correct, I could actually do that pretty easily. I could also add an opacity config option as well to go with it. I would have to test it just to make sure it is actually possible, but yeah, I could do that this update.

Yeah, I do like that idea though.

**Comment by BLUEChester** [comment]
Yeah, I personally really like the spark, I think it looks better underwater compared to on-land. But you're certainly right that it does pull the attention away, with a scale/opacity slider that effect could definitely be made better, but you might want to just aim to release it rather then constantly adding new things, up to you and what you think is right.

**Comment by Superkat32** [comment]
I think the sliders will probably be the last thing I add. It feels like a good thing to have upon initial release.

**Comment by Superkat32** [comment]
Sliders have been added and a WIP 1.19.4 port has just been started. Really the only things I have left is A: Play around with the bubbles movement just a little bit more, and B: Test all of the versions outside of the development environment. Also, I will try to get a 1.20 pre-release 2 port started this Wednesday, assuming it comes out and Fabric is able to update this Wednesday.

**Comment by Superkat32** [comment]
Added in Explosive Enhancement v1.1.0. Thank you, both BLUEChester and IceBlossom, for giving feedback on this effect and helping it look really good!
